### ISSUE TITLE
Instalar el módulo simple_fb_connect

### ISSUE THREAD

**Issue by acarrasco-rmla** [RealMediaNetworks/cencosudshop#38]
Instalar el módulo simple_fb_connect, que se utiliza para configurar el login a través de Facebook.

**Comment by translector** [comment]
Módulo agregado a composer.

**Comment by translector** [comment]
https://github.com/RealMediaNetworks/cencosudshop/pull/39

**Comment by translector** [comment]
Módulo agregado a composer.json detalles en https://github.com/RealMediaNetworks/cencosudshop/pull/39
